# Generated by Django 4.1.7 on 2023-04-01 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0003_device_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AtmoshphericHumidity', models.FloatField()),
                ('AtmoshphericTemperature', models.FloatField()),
                ('SoilHumidity', models.FloatField()),
                ('SoilTemperature', models.FloatField()),
                ('deviceId', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='mqtt.device')),
            ],
        ),
    ]
