# Generated by Django 4.1.7 on 2023-04-01 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0005_alter_sensordata_deviceid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordata',
            old_name='AtmoshphericHumidity',
            new_name='AtmosphericHumidity',
        ),
        migrations.RenameField(
            model_name='sensordata',
            old_name='AtmoshphericTemperature',
            new_name='AtmosphericTemperature',
        ),
    ]
