# Generated by Django 4.1.7 on 2023-04-01 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0006_rename_atmoshpherichumidity_sensordata_atmospherichumidity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 4, 1, 16, 42, 8, 125108, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
