# Generated by Django 4.1.7 on 2023-04-01 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0009_alter_sensordata_deviceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='deviceId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mqtt.device'),
        ),
    ]
