# Generated by Django 4.1.7 on 2023-04-01 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0011_devicecontrolactivity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicecontrolactivity',
            old_name='device',
            new_name='deviceId',
        ),
    ]
